runner-be/RunnerBe-Android

- app/src/main/java/com/applemango/runnerbe/data/dto/Posting.kt
- app/src/main/java/com/applemango/runnerbe/data/dto/UserInfo.kt
- app/src/main/java/com/applemango/runnerbe/data/network/api/AttendanceAccessionApi.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/mypost/accession/AttendanceAccessionViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/mypost/accession/MyPostAttendanceAccessionFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/mypost/accession/MyPostAttendanceAccessionViewModel.kt
- app/src/main/java/com/applemango/runnerbe/util/DateUtil.kt
- app/src/main/res/drawable/selector_primary_g4_checked.xml
- app/src/main/res/layout/fragment_my_post_attendance_accession.xml
- app/src/main/res/layout/item_attendance_accession.xml
- app/src/main/res/values/strings.xml
출석체크 API 연동(timeOut으로 인해 테스트 불가)
> TC - 출석체크 API 연동

- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/additionalinfo/terms/AgreeToTermsFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/base/WebViewFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/base/WebViewViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/main/MainFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/setting/SettingFragment.kt
- app/src/main/res/layout/fragment_settings.xml
- app/src/main/res/layout/fragment_web_view.xml
- app/src/main/res/navigation/nav_additional_info.xml
- app/src/main/res/navigation/nav_main.xml
- app/src/main/res/values/strings.xml
> UI - 약관 웹뷰 추가

- app/src/main/java/com/applemango/runnerbe/RunnerBeApplication.kt
- app/src/main/java/com/applemango/runnerbe/data/network/FireBaseModule.kt
- app/src/main/java/com/applemango/runnerbe/data/repositoryimpl/RunningTalkRepositoryImpl.kt
- app/src/main/java/com/applemango/runnerbe/domain/repository/RunningTalkRepository.kt
> TC - 파이어베이스 토큰 전송

- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/paceinfo/PaceInfoRegistFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/paceinfo/PaceInfoViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/paceinfo/PaceSelectItem.kt
- app/src/main/java/com/applemango/runnerbe/util/ViewBindingAdapter.kt
> TC - 프래그먼트 기능 추가

- app/src/main/java/com/applemango/runnerbe/data/network/request/SendMessageRequest.kt
- app/src/main/java/com/applemango/runnerbe/data/repositoryimpl/RunningTalkRepositoryImpl.kt
- app/src/main/java/com/applemango/runnerbe/domain/repository/RunningTalkRepository.kt
- app/src/main/java/com/applemango/runnerbe/domain/usecase/runningtalk/MessageSendUseCase.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/detail/RunningTalkDetailListAdapter.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/detail/RunningTalkDetailViewModel.kt
- app/src/main/res/layout/fragment_running_talk_detail.xml
> TC - 이미지 업로드 기능 추가

- app/src/main/java/com/applemango/runnerbe/util/LogUtil.kt
<h1>로그 작성 편의성을 위한 유틸 클래스 작성</h1>
1. Error log
2. Debug log
> RunningLog | LogUtil 추가

- app/build.gradle
- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/camera/CameraDialog.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/camera/CameraOptionSelectListener.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/RunningLogFragment.kt
- app/src/main/java/com/applemango/runnerbe/util/ViewBindingAdapter.kt
- app/src/main/java/com/applemango/runnerbe/util/manager/PermissionManager.kt
- app/src/main/java/com/applemango/runnerbe/util/manager/SinglePhotoManager.kt
- app/src/main/res/layout/dialog_camera.xml
- app/src/main/res/values/strings.xml
1. 이미지 단일 선택 Manager 클래스 작성
2. 권한 관리 Manager 클래스 작성
3. 러닝로그 작성 시 촬영/선택 및 권한 요청, 이미지 출력 및 저장기능 구현
> RunningLog | 이미지 추가/조회

- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/stamp/StampBottomSheetDialog.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/weather/WeatherBottomSheetDialog.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/weather/WeatherItem.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/GotStampAdapter.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/GroupProfilesFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/ProfileAdapter.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/RunningLogDetailViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/RunningLogFragment.kt
- app/src/main/res/values/strings.xml
[기능 개선]
1. 스탬프 및 날씨 바텀 시트 출력 시 기존 선택 아이템이 보이게 스크롤되는 기능 추가
[UX 개선]
1. 날씨 바텀 시트 등록 버튼 클릭 시, 기온이 미입력된 상태라면 닫힘 방지 및 토스트 출력
> RunningLog | 스탬프/날씨 기능 및 UX 개선

- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/MyPageFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/MyPageViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/WeeklyCalendarFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/WeeklyCalendarPagerAdapter.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/DateItem.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/UserProfileFragment.kt
- app/src/main/res/layout/fragment_mypage.xml
1. 주간 러닝 로그 뷰페이저 적용
2. 러닝 로그 데이터 적용 방식 변경(뷰페이저 프래그먼트로 위임 - activityViewModel)
3. 주간 러닝 로그 클릭 후 popBackStack 시 뷰페이저 포지션 2로 초기화되던 현상 수정(position 유지되도록 변경)
> MyPage | 주간 러닝 로그 뷰페이저 추가 및 개선

- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/stamp/StampAdapter.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/stamp/StampBottomSheetDialog.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/weather/WeatherAdapter.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/map/filter/RunningFilterFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/MyPageFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/groupprofile/GroupProfilesFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/write/RunningLogFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/write/RunningLogViewModel.kt
- app/src/main/res/layout/fragment_running_filter.xml
- app/src/main/res/layout/fragment_running_log.xml
- app/src/main/res/layout/item_stamp.xml
[러닝로그]
1. 개인 로그 작성 시 Check 스탬프 이외의 다른 스탬프도 선택 가능한 오류 수정
-> 다른 스탬프 선택 시 토스트 노출 
2. 개인 로그 작성 시 함께한 러너 목록(테스트 목적으로 설정되었던)으로 이동할 수 있던 오류 수정
[마이페이지]
1. 주간 캘린더 하단의 러닝 로그 통계에 그룹 0회 개인 0회라고 표시되던 오류 수정
[필터]
1. 페이스 난이도 우측 인포 버튼 클릭 시 페이스 난이도에 대한 설명 툴팁 노출되도록 수정
> 스프린트2 QA 개선사항 적용(마이페이지, 러닝로그, 필터)

- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/write/RunningLogViewModel.kt
[러닝 로그]
1. 날씨 온도 값 미입력 상태에서 - 텍스트 노출되도록 수정
> 러닝 로그 UI 개선

- app/build.gradle
- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/dateselect/DateTimePickerDialog.kt
[게시글 작성]
1. 현재 날짜가 선택되어 있는 경우, 현재 시간 이전의 시간을 선택한다면 확인버튼 클릭 시 토스트 노출되도록 수정
> 게시글 작성 시 현재시간 이전 시간은 선택 불가능하도록 수정

- app/src/main/java/com/applemango/runnerbe/data/vo/RunningWriteTransferData.kt
- app/src/main/java/com/applemango/runnerbe/presentation/model/DateResultListener.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/dateselect/DateTimePickerDialog.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/map/address/AddressViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/map/write/RunningWriteOneFragment.kt
- app/src/main/java/com/applemango/runnerbe/util/ViewBindingAdapter.kt
- app/src/main/res/layout/fragment_running_write_two.xml
- app/src/main/res/layout/item_address.xml
- app/src/main/res/values/strings.xml
[게시글 작성]
1. 주소 검색 결과 아이템 데이터 바인딩 적용
2. 모임 날짜-시간 선택 다이얼로그에 표시되는 데이터 수정
3. 주소 미등록 상태에서 표시되는 문구 변경
4. 선택된 모임 인원이 8명일 경우 최대 8명까지 선택 가능하다는 문구 노출
[오류 수정]
1. 게시글 작성 1단계->2단계->메인화면->작성 1단계 이동 시, 이전에 작성한 게시글 데이터 남아있는 오류 수정
-> 뷰모델 범위가 액티비티로 되어있어 발생한 문제
> 러닝 게시글 작성 로직 개선

- app/src/main/java/com/applemango/runnerbe/di/AdapterModule.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/RunningTalkAdapter.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/RunningTalkFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/RunningTalkViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/RunningTalkViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/map/RunnerMapViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/map/address/RunningAddressSearchFragment.kt
- app/src/main/java/com/applemango/runnerbe/util/ListBindingAdapter.kt
- app/src/main/res/layout/fragment_main.xml
- app/src/main/res/layout/fragment_running_talk.xml
- app/src/main/res/navigation/nav_main.xml
[러닝톡]
1. 채팅방 이동 애니메이션 추가
2. 데이터바인딩 어댑터 제거
[메인]
1. 최상위 ViewGroup Linear -> Constraint로 변경
[코드 정리]
1. 디버깅 코드 제거
> 러닝톡 개선 및 코드 정리

- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/RunningTalkDetailClickListener.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/RunningTalkViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/detail/RunningTalkDetailFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/detail/RunningTalkDetailListAdapter.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/detail/RunningTalkDetailMyContainerViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/detail/RunningTalkDetailOtherContainerViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/detail/RunningTalkDetailViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/detail/image/preview/RunningTalkDetailImageAdapter.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/detail/mapper/RunningTalkDetailMapper.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/map/RunnerMapViewModel.kt
- app/src/main/java/com/applemango/runnerbe/util/manager/SinglePhotoManager.kt
- app/src/main/res/layout/fragment_running_talk_detail.xml
[러닝톡]
1. 상세화면 하단 레이아웃 터치 범위 확장 및 위치 조정
2. 상세화면 메시지 클릭 리스너 추가
3. 코드 정리
[공통]
1. 코드 정리
> 러닝톡 레이아웃 수정 및 코드 정리

- app/src/main/res/layout/fragment_mypage.xml
- app/src/main/res/layout/fragment_running_talk.xml
- app/src/main/res/layout/fragment_running_write_two.xml
- app/src/main/res/layout/item_join_post_with_bookmark.xml
[Post]
1. 항목 간 마진 값 수정
2. 페이스 텍스트 우측 마진 추가
[RunningTalk]
1. 오버 스크롤 모드 제거
[PostingWrite]
1. 모임 인원 2/8명 아닐 경우 divider 마진 값 수정
[MyPage]
1. 참여한 러닝 없을 경우 노출되는 텍스트 값 범위 수정
> 1차 디자인 QA 변경사항 적용

- app/src/main/java/com/applemango/runnerbe/data/vo/MapFilterData.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/map/filter/RunningFilterFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/map/filter/RunningFilterViewModel.kt
- app/src/main/java/com/applemango/runnerbe/util/ViewBindingAdapter.kt
- app/src/main/res/drawable/ic_red_dot_7.xml
- app/src/main/res/drawable/ic_red_dot_with_stroke.xml
- app/src/main/res/layout/fragment_running_filter.xml
- app/src/main/res/values/strings.xml
[필터]
1. 변경사항 존재/미존재 시 적용되는 필터 이미지 변경 및 추가
2. 필터 초기화 버튼 클릭 시 "페이스 난이도" 항목만 초기화되지 않던 오류 수정
3. 페이스 난이도 미선택 시에도 이전 화면으로 돌아갈 수 있으며, 페이스 필터가 적용되지 않은 리스트가 노출되는 오류 수정
> 필터 기능 개선 및 오류 수정

- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/map/write/RunningWriteOneFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/map/write/RunningWriteOneViewModel.kt
[게시글 작성]
1. 진입 시 초기 설정되는 일시가 현재 시간보다 이전임에도 다음 단계로 이동 가능한 현상 수정
> 게시글 작성 비정상 동작 수정

- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/dateselect/DateTimePickerDialog.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/MyPageFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/MyPageViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/write/RunningLogFragment.kt
- app/src/main/java/com/applemango/runnerbe/util/NumberUtil.kt
- app/src/main/res/layout/fragment_running_log.xml
- app/src/main/res/navigation/nav_main.xml
[Mypage]
1. 참여한 러닝 북마크 클릭 시 상태 변경 및 전체 적용
2. 아이템 클릭 리스너 추가
[RunningLog]
1. 현재 시각 pm - 12 선택할 경우 크래시 나는 현상 수정
2. 현재 시각 pm - 12 선택할 경우 현재 시각이 오늘 pm - 11임에도 적용되는 현상 수정
-> ex) 현재 시각이 밤 11시 임에도 오후 12시가 선택 가능한 현상 수정
[PostingWrite]
1. 스탬프 디폴트 이미지 클릭 시 스탬프 바텀시트가 노출되지 않는 현상 수정
2. EditText 500자까지 입력 가능하도록 수정
> 마이페이지/러닝로그 오류 수정

- app/src/main/java/com/applemango/runnerbe/data/network/response/UserDataResponse.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/compose/login/SplashViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/dateselect/DateTimePickerDialog.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/MyPageFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/MyPageViewModel.kt
- app/src/main/java/com/applemango/runnerbe/util/DateUtil.kt
- app/src/main/java/com/applemango/runnerbe/util/ViewBindingAdapter.kt
[Posting]
1. 소요 시간 표기 변경
2. 모임 시간이 설정된 시간과 다르게 표기되는 현상 수정
[PostingWrite]
1. 지나지 않은 시간 선택시에도 선택이 불가능하던 현상 수정
[Mypage]
1. 간헐적으로 사용자가 약관 동의를 하지 않은 상태임에도 팝업이 노출되지 않음
-> 이 경우 UserInfo가 Null 값이므로 Nullable 처리 추가
> 게시글 시간 표기 수정 / 오류 수정

- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/joinedrunning/JoinedRunningFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/joinedrunning/JoinedRunningViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/otheruser/OtherUserProfileFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/otheruser/OtherUserProfileViewModel.kt
- app/src/main/res/layout/fragment_joined_running.xml
- app/src/main/res/layout/fragment_other_user_profile.xml
- app/src/main/res/layout/fragment_post_detail.xml
- app/src/main/res/layout/fragment_running_log.xml
- app/src/main/res/layout/item_runner_info.xml
- app/src/main/res/layout/item_waiting_runner_info.xml
[Posting]
1. 신청한 러너 버튼 우측 하단에 고정되도록 수정
2. 신청한 러너 페이스 태그/출석 태그 추가 및 디자인 수정
[OtherUserProfile]
1. 주간 캘린더 뷰페이저 적용
2. 하단 도트 인디케이터 추가
[RunningLog]
1. EditText 높이 늘어나면 하단부 레이아웃 잘리는 현상 수정
[JoinedRunning]
1. 상단 탭 클릭 시 리스트가 필터링되지 않는 현상 수정 -> throttleFirst로 인해 발생한 문제
2. 게시글 상세 이동 후 뒤로가기로 돌아오면 기존 선택된 탭이 아닌 default 값으로 초기화되던 현상 수정
> QA - 기능 개선 및 오류 수정

- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/detail/RunningTalkDetailViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/MyPageFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/weekly/WeeklyCalendarFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/weekly/WeeklyCalendarPagerAdapter.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/otheruser/OtherUserProfileFragment.kt
- app/src/main/res/layout/item_attendance_accession.xml
- app/src/main/res/layout/item_attendance_see.xml
- app/src/main/res/layout/item_runner_info.xml
- app/src/main/res/layout/item_waiting_runner_info.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
[RunningTalk]
1. 이미지 전송 로직 최적화
[OtherUserProfile]
1. 주간 캘린더 클릭 리스너 제거
[Common]
1. 참여자 배너 레이아웃 통일 -> style.xml 작성
> 러닝톡 기능 개선 및 레이아웃 스타일 적용

- app/src/main/java/com/applemango/runnerbe/data/network/response/MonthlyStampResponse.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/MyPageViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/monthly/MonthlyCalendarFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/monthly/MonthlyDateViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/weekly/WeeklyCalendarFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/weekly/WeeklyDateViewHolder.kt
- app/src/main/res/layout/fragment_mypage.xml
[Mypage]
1. 참여한 러닝 배너 최신순 정렬 
2. 참여한 러닝 리사이클러뷰 상단 패딩 제거
3. 러닝 로그 작성 가능일자 표시 기능 추가
> 마이페이지 오류 수정

- app/src/main/java/com/applemango/runnerbe/data/network/request/RunningLogRequest.kt
- app/src/main/java/com/applemango/runnerbe/data/network/response/MonthlyStampResponse.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/dateselect/DateTimePickerDialog.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/detail/RunningTalkDetailMyContainerViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/map/RunnerMapFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/monthly/MonthlyCalendarFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/monthly/MonthlyDateViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/weekly/WeeklyCalendarFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/joinedrunning/JoinedRunningPostViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/mypost/accession/AttendanceAccessionViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/mypost/accession/MyPostAttendanceAccessionFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/otheruser/OtherUserProfileViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/write/RunningLogViewModel.kt
[Mypage]
1. 그룹 로그 작성 후에도 그룹 로그 작성 가능 스탬프가 보여지며, 작성 시 오류 토스트 출력하는 현상 수정
> 마이페이지 그룹 런닝로그 오류 수정

- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/stamp/StampBottomSheetDialog.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/stamp/StampItem.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/monthly/MonthlyCalendarFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/monthly/MonthlyDateViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/weekly/WeeklyCalendarFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/weekly/WeeklyDateViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/detail/RunningLogDetailFragment.kt
- app/src/main/res/layout/fragment_post_detail.xml
- app/src/main/res/layout/fragment_running_log_detail.xml
- app/src/main/res/navigation/nav_main.xml
- app/src/main/res/values/styles.xml
[OtherUserProfile] 
1. 다른 사람 러닝로그 조회 시 - gatheringId가 존재해도 - 변경 불가능 얼굴 이미지로 표시되도록 수정
2. 다른 사람 러닝로그 조회 시 - 비공개 상태일 경우 - 스탬프 아이콘은 주간/월간 캘린더에 표시되도록 수정
[RunningLog]
1. lineHeight 값으로 인해 스탬프 설명 텍스트 개행 간격이 지나치게 좁은 현상 수정
2. 상세 화면 진입 시 - 자신의 로그에는 공개여부 표시/다른 사람의 로그에는 공개여부 미표시 되도록 수정
[PostingDetail]
1. 참여한 러너 리사이클러뷰 상단 마진 제거
> 다른 사람 프로필 조회 기능 개선

- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/weekly/WeeklyCalendarFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/joinedrunning/JoinedRunningFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/joinedrunning/JoinedRunningViewModel.kt
- app/src/main/res/layout/fragment_mypage.xml
- app/src/main/res/layout/fragment_other_user_profile.xml
- app/src/main/res/layout/fragment_runner_map.xml
- app/src/main/res/layout/item_attendance_accession.xml
- app/src/main/res/layout/item_other_image_talk.xml
[JoinedRunning]
1. 출석 관리하기 화면에서 출석 등급 이미지 대신 페이스 등급 이미지가 보이는 현상 수정
2. 북마크 상태 변경되지 않던 현상 수정
[Mypage]
1. 다른 사람 프로필 화면에서 페이스/출석 등급 레이아웃 수정
2. 주간 캘린더에서 비공개 상태의 러닝 로그는 스탬프도 표시되지 않던 현상 수정
> 다른 사람 프로필/참여한 러닝 오류 수정

- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/stamp/StampBottomSheetDialog.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/stamp/StampItem.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/monthly/MonthlyCalendarFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/monthly/MonthlyDateViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/weekly/WeeklyDateViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/detail/RunningLogDetailFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/detail/RunningLogDetailViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/groupprofile/GroupProfilesFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/groupprofile/GroupProfilesViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/write/RunningLogFragment.kt
- app/src/main/java/com/applemango/runnerbe/util/ViewBindingAdapter.kt
- app/src/main/res/layout/fragment_running_log.xml
- app/src/main/res/layout/fragment_running_log_detail.xml
- app/src/main/res/values/strings.xml
**[Calendar]**
1. 그룹 로그 작성 가능한 날짜에 그룹 로그가 작성되어 있어도 
그룹 로그 작성 가능 스탬프가 보여지는 현상 수정
2. 주간/월간 캘린더에서 비공개 로그가 작성된 날짜 클릭 시 토스트 노출
**[RunningLog]**
1. 데이터바인딩 적용
2. 그룹 로그 작성 시 함께한 러너 명수 표기되도록 수정
3. 함게한 러너 화면에서 스탬프가 설정되지 않은 러너 클릭 시 크래시나는 현상 수정(Nullable 처리 추가)
> 러닝로그 데이터바인딩 수정 및 캘린더 그룹 로그 오류 수정

- app/src/main/java/com/applemango/runnerbe/data/network/response/RunningLogDetailResponse.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/MyPageFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/MyPageViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/joinedrunning/JoinedRunningViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/detail/GotStampAdapter.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/detail/RunningLogDetail.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/detail/RunningLogDetailFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/otheruser/OtherUserJoinedPostViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/otheruser/OtherUserProfileFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/otheruser/OtherUserProfileViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/write/RunningLogViewModel.kt
- app/src/main/java/com/applemango/runnerbe/util/ViewBindingAdapter.kt
- app/src/main/res/layout/fragment_post_detail.xml
- app/src/main/res/layout/fragment_running_log.xml
- app/src/main/res/layout/fragment_running_log_detail.xml
- app/src/main/res/layout/item_got_stamp.xml
- app/src/main/res/layout/item_runner_info.xml
[RunningLog]
1. 함께한 러너에게 받은 스탬프 아이템 레이아웃 수정
2. 함께한 러너베에 받은 스탬프 이미지 보이지 않는 현상 수정
> 러닝로그 함께한러너 오류 수정

- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/joinedrunning/JoinedRunningPostViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/detail/RunningLogDetailFragment.kt
- app/src/main/res/layout/fragment_running_log_detail.xml
- app/src/main/res/navigation/nav_main.xml
[JoinedRunning]
1. 서버 응답값으로 받는 ZonedDateTime 값이 시간은 KST이지만 형식은 UTC로 오기 때문에
현재 시간과 비교하는 로직에 문제가 발생하여 "출석 관리하기" 버튼이 보이지 않던 현상 수정
[RunningLog]
1. 그룹 로그 -> 러닝 로그 상세 화면에서도 함께한 러너 클릭 시 해당 화면으로 이동하도록 수정
> 참여한 러닝 상태 오류 수정

- app/src/main/java/com/applemango/runnerbe/data/network/response/KakaoAddressResponse.kt
- app/src/main/java/com/applemango/runnerbe/data/paging/AddressSearchPagingSource.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/map/address/RunningAddressSearchFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/detail/RunningLogDetailViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/write/RunningLogFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/write/RunningLogViewModel.kt
- app/src/main/java/com/applemango/runnerbe/util/AddressUtil.kt
- app/src/main/java/com/applemango/runnerbe/util/ViewBindingAdapter.kt
- app/src/main/res/layout/fragment_running_log.xml
- app/src/main/res/layout/item_group_profile.xml
[RunningLog]
1. 스탬프 바텀 시트가 보여질 때, 첫번째 아이템이 선택되어 있으나 "선택"버튼 클릭 시 "스탬프를 선택해주세요"라는 토스트가 노출되는 현상 수정
2. 그룹 로그 작성 시에, "흑백 스탬프 추가 이미지" 대신 "노란색 스탬프 추가 이미지"가 보여지도록 개선
[PostingWrite]
1. 카카오; 주소 검색 API 응답객체의 x와 y가 longitude-latitude 순서이나, 기존 응답객체가 latitude-longitude로 작성되어 있어 지도 마커 생성 메서드에서 IllegalArgumentException 발생하는 현상 수정
> 러닝로그 UI/UX 개선 및 게시글 작성 오류 수정

- app/build.gradle
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/detail/RunningTalkDetailViewModel.kt
- app/src/main/java/com/applemango/runnerbe/util/AddressUtil.kt
- app/src/main/java/com/applemango/runnerbe/util/ViewBindingAdapter.kt
- app/src/main/res/layout/fragment_post_detail.xml
[Posting]
1. 주소 영역에 상세 주소 전체가 표시되도록 수정
2. 경도=위도 기반 주소 검색 시, 결과가 없는 경우에 상단바에 null이라는 텍스트가 보여지는 현상 수정
[RunningTalk]
1. 이미지 전송 시, 톡 리스트가 바로 갱신되지 않는 현상 수정
> 게시글 정보 표기 개선, 러닝톡 로직 개선

- app/src/main/java/com/applemango/runnerbe/data/dto/Posting.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/MyPageFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/joinedrunning/JoinedRunningFragment.kt
- app/src/main/java/com/applemango/runnerbe/util/ViewBindingAdapter.kt
- app/src/main/res/layout/fragment_running_write.xml
- app/src/main/res/layout/item_group_profile.xml
- app/src/main/res/layout/item_join_post_with_bookmark.xml
- app/src/main/res/navigation/nav_main.xml
[JoinedRunning]
1. 해당 날짜의 로그 작성 여부에 따라 로그 보기/로그 쓰기로 텍스트 변경되도록 수정
> 참여한 러닝 로그 쓰기/보기 버튼 관련 오류 수정

- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/RunningTalkViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/paceinfo/PaceInfoRegistFragment.kt
- app/src/main/res/layout/dialog_waiting_runnuer_list.xml
- app/src/main/res/layout/fragment_group_profiles.xml
- app/src/main/res/navigation/nav_main.xml
- app/src/main/res/values/strings.xml
[RunningLog]
1. 함께한 러너 화면으로 이동할 때 슬라이드 애니메이션 적용
[GroupProfile]
1. 리사이클러뷰 상단 마진 값 변경
[Mypage]
1. 페이스 별 이름 수정
[RunningTalk]
1. 러닝톡 채팅방 목록이 최신순으로 정렬되도록 수정
[PostDetail]
1. 신청한 러너 다이얼로그 하단 버튼 영역 paddingVertical 값 변경
> 페이스 별 이름 수정 및 레이아웃 속성 수정

- app/src/main/java/com/applemango/runnerbe/presentation/screen/dialog/appliedrunner/WaitingRunnerListDialog.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/detail/RunningLogDetailViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/groupprofile/GroupProfilesFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/groupprofile/ProfileAdapter.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/otheruser/OtherUserProfileClickListener.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/write/RunningLogFragment.kt
- app/src/main/java/com/applemango/runnerbe/util/ViewBindingAdapter.kt
- app/src/main/res/layout/fragment_running_log_detail.xml
- app/src/main/res/layout/item_group_profile.xml
- app/src/main/res/layout/item_pace_select.xml
- app/src/main/res/navigation/nav_main.xml
[PostDetail]
1. 신청한 러너 클릭 시 해당 사용자 마이페이지로 이동하도록 수정
[RunningLog]
1. 스탬프 미선택 상태 토스트 문구 변경
2. 함께한 러너 명수가 데이터와 다른 현상 수정
[GroupProfile]
1. 함께한 러너 닉네임 글자 제한 제거 후 끝 말줄임표 활성화되도록 수정
2. 해당 그룹 러닝에 대한 로그 존재 여부/공개 여부에 따라 로그 보기/비활성화/비공개 상태 분기 처리 추가
> 함께한 러너 로그 보기 추가 및 사용성 개선(신청한 러너, 러닝 로그)

- app/build.gradle
- app/src/main/java/com/applemango/runnerbe/data/network/request/RunningLogRequest.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/chat/detail/image/detail/ImageDetailFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/detail/RunningLogDetailFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/write/RunningLogViewModel.kt
- app/src/main/java/com/applemango/runnerbe/util/manager/SinglePhotoManager.kt
- app/src/main/res/layout/fragment_image_detail.xml
- app/src/main/res/layout/fragment_running_log_detail.xml
- app/src/main/res/navigation/nav_main.xml
[RunningLog]
1. 러닝 로그 작성 시, 파이어베이스에 해당 이미지 저장한 후 반환된 url을 러닝 로그 등록 시 포함하여 저장하도록 수정
2. 이미지 크롭 기능 적용 보류
3. 러닝 로그 상세 화면에서 이미지 클릭 시 이미지 상세 화면으로 이동하도록 수정
> 러닝 로그 작성 시 이미지 등록 추가 및 이미지 상세 화면 이동 구현

- app/src/main/java/com/applemango/runnerbe/data/dto/Posting.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/map/write/RunningWriteTwoViewModel.kt
[Post]
1. 기존 TimeFormat을 kk로 사용하여 발생한 오류
-> 00시에 게시글 작성 시, 24:35:00 과 같이 저장되어 발생하는 오류 수정 (HH로 변경)
> 게시글 작성 시 TimeFormat 수정

- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/detail/GotStampAdapter.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/detail/GotStampClickListener.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/detail/GotStampItem.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/detail/RunningLogDetailFragment.kt
- app/src/main/res/layout/item_got_stamp.xml
- app/src/main/res/navigation/nav_main.xml
[RunningLog]
1. 다른 사용자에게 받은 스탬프 목록에서, 스탬프 클릭 시 해당 유저 프로필로 이동하도록 수정
> 받은 스탬프 클릭 시 해당 유저 프로필로 이동 가능하도록 수정

- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/groupprofile/ProfileAdapter.kt
- app/src/main/res/layout/item_group_profile.xml
[GroupProfile]
1. 각 사용자 프로필 사진 여백 생기는 현상 수정
2. 클릭 리스너 WeakReference 적용
> 함께한 러너 화면 사용성 개선

- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/map/RunnerMapFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/MyPageFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/MyPageViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/detail/GotStampAdapter.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/detail/GotStampViewHolder.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/runninglog/groupprofile/ProfileAdapter.kt
[RunningLog]
1. 받은 스탬프 어댑터 inner class에서 외부 클래스 변경
[Map]
1. onStart 시에 게시글 갱신되도록 수정
[Mypage]
1. onStart 시에 데이터 갱신되도록 수정
> 데이터 갱신 로직 추가 및 뷰홀더 클래스 분리

- app/src/main/java/com/applemango/runnerbe/data/network/api/GetAlarmsApi.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/map/RunnerMapFragment.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/map/RunnerMapViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/MyPageViewModel.kt
- app/src/main/java/com/applemango/runnerbe/presentation/screen/fragment/mypage/calendar/weekly/WeeklyCalendarFragment.kt
[Map]
1. 새로고침 시마다 기존 리스트 데이터가 중첩되는 현상 수정
[Calendar]
1. Bundle 객체에 대한 참조를 가지는 arg 변수의 메모리에 반복 접근하던 로직을 apply 함수 내부에서 컨텍스트로 처리하도록 수정
> 게시글 목록 오류 수정 및 코드 정리
